### ISSUE TITLE
Crash when pressed take picture button

### ISSUE THREAD

**Issue by sexol123** [JessYanCoding/InsGallery#15]
D/Camera2CameraImpl: mMeteringRepeating is ATTACHED, SessionConfig Surfaces: 2, CaptureConfig Surfaces: 1
D/UseCaseAttachState: Active and attached use case: [ImageCapture95977066] for camera: 1
D/UseCaseAttachState: All use case: [Preview101601115, ImageCapture95977066] for camera: 1
D/UseCaseAttachState: Active and attached use case: [ImageCapture95977066] for camera: 1
D/UseCaseAttachState: Active and attached use case: [Preview101601115, ImageCapture95977066] for camera: 1
D/UseCaseAttachState: Active and attached use case: [Preview101601115, ImageCapture95977066] for camera: 1
D/UseCaseAttachState: Active and attached use case: [Preview101601115, ImageCapture95977066] for camera: 1
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NoSuchMethodError: No virtual method takePicture(Ljava/io/File;Ljava/util/concurrent/Executor;Landroidx/camera/core/ImageCapture$OnImageSavedCallback;)V in class Landroidx/camera/view/CameraView; or its super classes (declaration of 'androidx.camera.view.CameraView' appears in /data/app/com.localise.app-25mD_WMiY_l9EwY8_Lc1OQ==/base.apk)
        at com.luck.picture.lib.instagram.InstagramCameraView$1.takePictures(InstagramCameraView.java:103)
        at com.luck.picture.lib.instagram.InstagramCaptureLayout.onTouchEvent(InstagramCaptureLayout.java:200)
        at android.view.View.dispatchTouchEvent(View.java:12527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1835)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
        at android.view.View.dispatchPointerEvent(View.java:12768)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5287)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5087)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4621)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4761)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4629)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4818)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4621)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4629)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7330)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7299)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7260)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7436)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
    	at java.lang.reflect.Method.i
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.localise.app, PID: 19402
    java.lang.NoSuchMethodError: No virtual method takePicture(Ljava/io/File;Ljava/util/concurrent/Executor;Landroidx/camera/core/ImageCapture$OnImageSavedCallback;)V in class Landroidx/camera/view/CameraView; or its super classes (declaration of 'androidx.camera.view.CameraView' appears in /data/app/com.localise.app-25mD_WMiY_l9EwY8_Lc1OQ==/base.apk)
        at com.luck.picture.lib.instagram.InstagramCameraView$1.takePictures(InstagramCameraView.java:103)
        at com.luck.picture.lib.instagram.InstagramCaptureLayout.onTouchEvent(InstagramCaptureLayout.java:200)
        at android.view.View.dispatchTouchEvent(View.java:12527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1835)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
        at android.view.View.dispatchPointerEvent(View.java:12768)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5287)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5087)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4621)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4761)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4629)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4818)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4621)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4629)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7330)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7299)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7260)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7436)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
D/CaptureSession: CameraCaptureSession.onClosed()
I/Process: Sending signal. PID: 19402 SIG: 9

**Comment by sexol123** [comment]
Xiaomi Redmi Note 7, Android 9

**Comment by tallot13** [comment]
https://github.com/JessYanCoding/InsGallery/pull/20

**Comment by AzzadCodeBrain** [comment]
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NoSuchMethodError: No virtual method takePicture(Ljava/io/File;Ljava/util/concurrent/Executor;Landroidx/camera/core/ImageCapture$OnImageSavedCallback;)V in class Landroidx/camera/view/CameraView; or its super classes (declaration of 'androidx.camera.view.CameraView' appears in /data/app/com.example.demoimagepicker-gSnIU2qkRo9wCbeuNwMWNg==/base.apk)
        at com.luck.picture.lib.instagram.InstagramCameraView$1.takePictures(InstagramCameraView.java:106)
        at com.luck.picture.lib.instagram.InstagramCaptureLayout.onTouchEvent(InstagramCaptureLayout.java:204)
        at android.view.View.dispatchTouchEvent(View.java:13415)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3993)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
        at android.view.View.dispatchPointerEvent(View.java:13674)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5482)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5285)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7505)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7474)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7435)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7630)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
    	at java.lang.refle


**PLease share me dependance**

**Comment by AzzadCoddedbrain** [comment]
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NoSuchMethodError: No virtual method takePicture(Ljava/io/File;Ljava/util/concurrent/Executor;Landroidx/camera/core/ImageCapture$OnImageSavedCallback;)V in class Landroidx/camera/view/CameraView; or its super classes (declaration of 'androidx.camera.view.CameraView' appears in /data/app/com.example.demoimagepicker-Nnsac3seE3Eq7ug6TTaRvw==/base.apk)
        at com.luck.picture.lib.instagram.InstagramCameraView$1.takePictures(InstagramCameraView.java:106)
        at com.luck.picture.lib.instagram.InstagramCaptureLayout.onTouchEvent(InstagramCaptureLayout.java:204)
        at android.view.View.dispatchTouchEvent(View.java:13415)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3993)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
        at android.view.View.dispatchPointerEvent(View.java:13674)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5482)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5285)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7505)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7474)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7435)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7630)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
    	at java.lang.refle


![error](https://user-images.githubusercontent.com/124251218/229276271-983a92a6-1a24-446e-9ed0-295649e3ee7f.png)


Solution CameraX lib 

Build.Gradle   

dependencies{

 // CameraX
    def camerax_version = "1.0.0-beta03"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"
    implementation "androidx.camera:camera-lifecycle:$camerax_version"
    implementation "androidx.camera:camera-view:1.0.0-alpha10"
    implementation "androidx.camera:camera-extensions:1.0.0-alpha10"

}
