### ISSUE TITLE
Crash when taking picture

### ISSUE THREAD

**Issue by jomarierafa** [JessYanCoding/InsGallery#31]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pixsell.carry.merchant, PID: 22091
    java.lang.NoSuchMethodError: No virtual method takePicture(Ljava/io/File;Ljava/util/concurrent/Executor;Landroidx/camera/core/ImageCapture$OnImageSavedCallback;)V in class Landroidx/camera/view/CameraView; or its super classes (declaration of 'androidx.camera.view.CameraView' appears in /data/app/com.pixsell.carry.merchant-w0vu_-5g_YXEKBHIQEVUNQ==/base.apk)
        at com.luck.picture.lib.instagram.InstagramCameraView$1.takePictures(InstagramCameraView.java:106)
        at com.luck.picture.lib.instagram.InstagramCaptureLayout.onTouchEvent(InstagramCaptureLayout.java:204)
        at android.view.View.dispatchTouchEvent(View.java:13484)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2767)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3110)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:498)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1853)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4059)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:456)
        at android.view.View.dispatchPointerEvent(View.java:13745)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5635)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5435)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4989)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4955)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5095)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4963)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5152)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4989)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4955)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4963)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7688)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7657)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7618)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7816)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:251)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by jomarierafa** [comment]
I'm importing this one
implementation "androidx.camera:camera-view:1.0.0-alpha019"

**Comment by noe** [comment]
You should use the same version of camerax as the one used by the version of InsGallery you are using. You can check this in file `config.gradle`. For instance, [InsGallery 0.7.0 uses camerax version 1.0.0-beta03](https://github.com/JessYanCoding/InsGallery/blob/v0.7.0/config.gradle#L20)
