### ISSUE TITLE
Crashes when capturing photo but video recording is working fine

### ISSUE THREAD

**Issue by HaXxanParhar** [JessYanCoding/InsGallery#48]
[complete_stacktrace.txt](https://github.com/JessYanCoding/InsGallery/files/6789561/complete_stacktrace.txt)
When capturing a photo it crashes with the following message (I attached the complete stack trace in the file) :

E/MessageQueue-JNI: java.lang.NoSuchMethodError: No virtual method takePicture(Ljava/io/File;Ljava/util/concurrent/Executor;Landroidx/camera/core/ImageCapture$OnImageSavedCallback;)V in class Landroidx/camera/view/CameraView; or its super classes (declaration of 'androidx.camera.view.CameraView' appears in /data/app/com.drudotstech.petsjoin-CVTNbQ33HjxYToUcHRdewA==/base.apk)
        at com.luck.picture.lib.instagram.InstagramCameraView$1.takePictures(InstagramCameraView.java:106)
        at com.luck.picture.lib.instagram.InstagramCaptureLayout.onTouchEvent(InstagramCaptureLayout.java:204)
        at android.view.View.dispatchTouchEvent(View.java:11788)  

Device: Huawei Honor 7C running Android 8.0.0

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/InsGallery/pull/20

upgrade camerax_view

**Comment by zhujiahong** [comment]
I have updated camera-view to 1.0.0-alpha14, but it still crashes when I take photos

**Comment by zhujiahong** [comment]
> [complete_stacktrace.txt](https://github.com/JessYanCoding/InsGallery/files/6789561/complete_stacktrace.txt)
> When capturing a photo it crashes with the following message (I attached the complete stack trace in the file) :
> 
> E/MessageQueue-JNI: java.lang.NoSuchMethodError: No virtual method takePicture(Ljava/io/File;Ljava/util/concurrent/Executor;Landroidx/camera/core/ImageCapture$OnImageSavedCallback;)V in class Landroidx/camera/view/CameraView; or its super classes (declaration of 'androidx.camera.view.CameraView' appears in /data/app/com.drudotstech.petsjoin-CVTNbQ33HjxYToUcHRdewA==/base.apk)
> at com.luck.picture.lib.instagram.InstagramCameraView$1.takePictures(InstagramCameraView.java:106)
> at com.luck.picture.lib.instagram.InstagramCaptureLayout.onTouchEvent(InstagramCaptureLayout.java:204)
> at android.view.View.dispatchTouchEvent(View.java:11788)
> 
> Device: Huawei Honor 7C running Android 8.0.0
I have same question. How did you solve it
