### ISSUE TITLE
视频录制的一个崩溃问题

### ISSUE THREAD

**Issue by zmemo** [JessYanCoding/InsGallery#5]
```
 Process: com.luck.pictureselector, PID: 7195
    android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1967)
        at android.media.MediaCodec.configure(MediaCodec.java:1896)
        at androidx.camera.core.VideoCapture.setupEncoder(VideoCapture.java:467)
        at androidx.camera.core.VideoCapture.onSuggestedResolutionUpdated(VideoCapture.java:242)
        at androidx.camera.core.UseCase.updateSuggestedResolution(UseCase.java:386)
        at androidx.camera.core.CameraX.bindToLifecycle(CameraX.java:317)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:229)
        at androidx.camera.view.CameraXModule.bindToLifecycleAfterViewMeasured(CameraXModule.java:242)
        at androidx.camera.view.CameraXModule.bindToLifecycle(CameraXModule.java:159)
        at androidx.camera.view.CameraXModule.rebindToLifecycle(CameraXModule.java:465)
        at androidx.camera.view.CameraXModule.setCaptureMode(CameraXModule.java:624)
        at androidx.camera.view.CameraView.setCaptureMode(CameraView.java:390)
        at com.luck.picture.lib.widget.instagram.InstagramCameraView$1.recordStart(InstagramCameraView.java:111)
        at com.luck.picture.lib.widget.instagram.InstagramCaptureLayout.dispatchLongPress(InstagramCaptureLayout.java:319)
        at com.luck.picture.lib.widget.instagram.InstagramCaptureLayout.access$000(InstagramCaptureLayout.java:31)
        at com.luck.picture.lib.widget.instagram.InstagramCaptureLayout$GestureHandler.handleMessage(InstagramCaptureLayout.java:278)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```
手机：华为 nova3i 安卓9
版本：0.1.7
可能原因：这个错误一般来说是在设置显示宽高为奇数的时候出现

**Comment by JessYanCoding** [comment]
PictureSelector 自己维护了一个 CameraView，我这也经常奔溃，我看他新版本已经用 google 官方的 CameraView 了，后面改过去应该就没问题了

**Comment by 1van** [comment]
```
if (mCameraView.getCaptureMode() != androidx.camera.view.CameraView.CaptureMode.VIDEO) {
    mCameraView.setCaptureMode(androidx.camera.view.CameraView.CaptureMode.VIDEO);
}
```
